/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cajas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jacomess
 */
public class cat_productos extends javax.swing.JFrame {

    /**
     * Creates new form cat_productos
     */
    public cat_productos() {
        initComponents();
        mostrardatos("");
        limpiar();
        this.jComboBox1.removeAllItems();
        try {
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM cat_unidad_medida");
            while(rs.next()){
                
              this.jComboBox1.addItem(rs.getInt("idcat_unidad_medida"));   
               
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(cat_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.jComboBox2.removeAllItems();
        try {
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM cat_departamento");
            while(rs.next()){
                
                this.jComboBox2.addItem(rs.getInt("id_departamento"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(cat_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
    }
    
   void limpiar(){
       
       id_producto.setText("");
       descuento_producto.setText("");
       id_u_medida.setText("");
       cantidad.setText("");
       precio_compra.setText("");
       precio_venta.setText("");
       id_departamento.setText("");
       cantidad_minima.setText("");
       iva.setText("");
       preci_mayoreo.setText("");
       ps_mayore.setText("");
       
        
    }
    
    void mostrardatos(String valor){
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id_producto");
        modelo.addColumn("descuento producto");
        modelo.addColumn("id_u_medida");
        modelo.addColumn("cantidad");
        modelo.addColumn("precio u compra");
        modelo.addColumn("precio_u_venta");
        modelo.addColumn("id_departamento");
        modelo.addColumn("cantidad minima");
        modelo.addColumn("iva");
        modelo.addColumn("precio u mayoreo");
         modelo.addColumn("precio s mayoreo");
        tb_producto.setModel(modelo);
        String sql="";
        if(valor.equals("")){
            
            sql="SELECT * FROM cat_productos";
            
        }
        else{
            sql="SELECT * FROM cat_productos WHERE id_producto='"+valor+"'";
        }
        String [] datos = new String[11];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                modelo.addRow(datos);
                
               
                
                
                
            }
            
            tb_producto.setModel(modelo);
            
        } catch (SQLException ex) {
            Logger.getLogger(cat_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_producto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descuento_producto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id_u_medida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precio_compra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        precio_venta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id_departamento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cantidad_minima = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        iva = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        preci_mayoreo = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_producto = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        txtbusca = new javax.swing.JTextField();
        mostrrar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ps_mayore = new javax.swing.JTextField();
        NUEVO = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        jMenuItem1.setText("modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CATALOGO DE PRODUCTOS");

        jLabel2.setText("ID PRODUCTO");

        id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_productoActionPerformed(evt);
            }
        });

        jLabel3.setText("DESCUENTO DE PRODUCTO");

        descuento_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuento_productoActionPerformed(evt);
            }
        });

        jLabel4.setText("ID UNIDAD  DE MEDIDA");

        id_u_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_u_medidaActionPerformed(evt);
            }
        });

        jLabel5.setText("CANTIDAD");

        jLabel6.setText("PRECIO U COMPRA");

        jLabel7.setText("PRECIO U VENTA");

        precio_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_ventaActionPerformed(evt);
            }
        });

        jLabel8.setText("ID DE DEPARTAMENTO");

        jLabel9.setText("CANTIDAD MINIMA");

        jLabel10.setText("IVA");

        jLabel11.setText("PRECIO U MAYOREO");

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        tb_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_producto.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tb_producto);

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        mostrrar.setText("MOSTRAR DATOS");
        mostrrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrrarActionPerformed(evt);
            }
        });

        actualizar.setText("ACTUALIZAR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel12.setText("PRECIO S MAYOREO");

        NUEVO.setText("NUEVO");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id_u_medida, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(precio_compra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(cantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iva, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cantidad_minima, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(id_departamento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(precio_venta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(preci_mayoreo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(descuento_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ps_mayore))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(guardar)
                                        .addGap(50, 50, 50)
                                        .addComponent(buscar)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mostrrar)
                                .addGap(49, 49, 49)
                                .addComponent(actualizar)
                                .addGap(18, 18, 18)
                                .addComponent(NUEVO))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(descuento_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(id_u_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cantidad)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(precio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cantidad_minima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(preci_mayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ps_mayore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(buscar)
                    .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrrar)
                    .addComponent(actualizar)
                    .addComponent(NUEVO))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_productoActionPerformed

    private void descuento_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuento_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descuento_productoActionPerformed

    private void id_u_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_u_medidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_u_medidaActionPerformed

    private void precio_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_ventaActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        
      

        try {
            
       PreparedStatement psd = cn.prepareStatement("INSERT INTO cat_productos (desc_producto,id_unidad_medida,cantidad,p_u_compra,p_u_venta,id_departamento,cantidad_min,iva,p_u_mayoreo,p_s_mayoreo) VALUES (?,?,?,?,?,?,?,?,?,?)");
           
            psd.setNString(1, descuento_producto.getText());
            psd.setNString(2, id_u_medida.getText());
            psd.setNString(3, cantidad.getText());
            psd.setNString(4, precio_compra.getText());
            psd.setNString(5, precio_venta.getText());
            psd.setNString(6, id_departamento.getText());
            psd.setNString(7, cantidad_minima.getText());
            psd.setNString(8, iva.getText());
            psd.setNString(9, preci_mayoreo.getText());
            psd.setNString(10, ps_mayore.getText());
            int n=psd.executeUpdate();
            mostrardatos("");
            if (n>0){
                
                JOptionPane.showMessageDialog(null, "registro guardado");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(cat_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        mostrardatos(txtbusca.getText());
    }//GEN-LAST:event_buscarActionPerformed

    private void mostrrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrrarActionPerformed
        // TODO add your handling code here:
        mostrardatos("");
    }//GEN-LAST:event_mostrrarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try {
            // TODO add your handling code here:

            PreparedStatement psd = cn.prepareStatement("UPDATE cat_productos SET desc_producto='"+descuento_producto.getText()+"',id_unidad_medida='"+id_u_medida.getText()+"',cantidad='"+cantidad.getText()+"',p_u_compra='"+precio_compra.getText()+"',p_u_venta='"+precio_venta.getText()+"',id_departamento='"+id_departamento.getText()+"',cantidad_min='"+cantidad_minima.getText()+"',p_u_mayoreo='"+preci_mayoreo.getText()+"',p_s_mayoreo='"+ps_mayore.getText()+"'WHERE id_producto='"+id_producto.getText()+"'");
            psd.executeUpdate();
            mostrardatos("");
        } catch (SQLException ex) {
            Logger.getLogger(cat_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int fila = tb_producto.getSelectedRow();
        if(fila>=0){
            
            id_producto.setText(tb_producto.getValueAt(fila, 0).toString());
            descuento_producto.setText(tb_producto.getValueAt(fila, 1).toString());
            id_u_medida.setText(tb_producto.getValueAt(fila, 2).toString());
            cantidad.setText(tb_producto.getValueAt(fila, 3).toString());
            precio_compra.setText(tb_producto.getValueAt(fila, 4).toString());
            precio_venta.setText(tb_producto.getValueAt(fila, 5).toString());
            id_departamento.setText(tb_producto.getValueAt(fila, 6).toString());
            cantidad_minima.setText(tb_producto.getValueAt(fila, 7).toString());
            iva.setText(tb_producto.getValueAt(fila, 8).toString());
            preci_mayoreo.setText(tb_producto.getValueAt(fila, 9).toString());
            ps_mayore.setText(tb_producto.getValueAt(fila, 10).toString());
            
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        int fila = tb_producto.getSelectedRow();
        
        String idp="";
        idp=tb_producto.getValueAt(fila, 0).toString();
        if(fila>=0){
            try {
                PreparedStatement psd = cn.prepareStatement("DELETE FROM cat_productos WHERE id_producto='"+idp+"'");
            psd.executeUpdate();
            mostrardatos("");
            } catch (SQLException ex) {
                Logger.getLogger(cat_productos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_NUEVOActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    try{
        
        
        Statement st=cn.createStatement();
        ResultSet rs=st.executeQuery("SELECT * FROM cat_unidad_medida WHERE idcat_unidad_medida='"+this.jComboBox1.getSelectedItem()+"'");
        rs.next();
        this.id_u_medida.setText(String.valueOf(rs.getInt("idcat_unidad_medida")));
        
    }  catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
     
    }          
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        try {
            // TODO add your handling code here:
            

            Statement st=cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM cat_departamento WHERE id_departamento='"+this.jComboBox2.getSelectedItem()+"'");
            rs.next();
            this.id_departamento.setText(String.valueOf(rs.getInt("id_departamento")));
            
        } catch (SQLException ex) {
            Logger.getLogger(cat_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cat_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cat_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cat_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cat_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cat_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NUEVO;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField cantidad_minima;
    private javax.swing.JTextField descuento_producto;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField id_departamento;
    private javax.swing.JTextField id_producto;
    private javax.swing.JTextField id_u_medida;
    private javax.swing.JTextField iva;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrrar;
    private javax.swing.JTextField preci_mayoreo;
    private javax.swing.JTextField precio_compra;
    private javax.swing.JTextField precio_venta;
    private javax.swing.JTextField ps_mayore;
    private javax.swing.JTable tb_producto;
    private javax.swing.JTextField txtbusca;
    // End of variables declaration//GEN-END:variables

   conecta cc = new conecta();
   Connection cn = cc.conexion();
    
}

